name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # 1. Install Flutter SDK (includes Dart), with pub cache
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      # 2. Install dependencies using Flutter command
      - name: Install dependencies
        run: flutter pub get

      # 3. Analyze code
      - name: Analyze project source
        run: flutter analyze

      # 4. Run tests
      - name: Run tests
        run: flutter test